### ISSUE TITLE
Ignore `<span ...>` and `</span>` tags

### ISSUE THREAD

**Issue by getreu** [nabbisen/mdka-rs#31]
In my use case, the [tpnote crate](https://github.com/getreu/tp-note) the input to the HTML to Markdown filter can contain arbitrary clipboard content, in many cases format instructions in `<span ....>` tags, e.g.:

```html
<span id="i3x-cke__body_347ca9c14da3cc5b1fe1ebdbb10f15ea" style="unicode-bidi: plaintext; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Cantarell; font-size: 14.705309px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0.4); -webkit-text-stroke-width: 0px; text-decoration: none;">
Some content
</span>
```

Could you silently ignore `<span ...>` and `</span>`? It does not add any semantics to the resulting Markdown, but it adds a lot of garbage noise when converting automatically generated HTML.Or, if not possible, add a feature to ignore them?

**Comment by nabbisen** [comment]
@getreu 
Hi :) Thank you for your opening it. tpnote is great !!!

> Could you silently ignore <span ...> and </span>? It does not add any semantics to the resulting Markdown, but it adds a lot of garbage noise when converting automatically generated HTML.

mdka preserves only attrs of `id` and `style`. I understood you situation, but it seems impossible, because enclosures such as `<span style="color: orange;">content</span>` sometimes works in `.md`. Not always, however sometimes.

> Or, if not possible, add a feature to ignore them?

I'll try to think. As I would like to keep code simple and minimal, I can't make promise to complete it. In case, you maybe need your html preprocessed.

**Comment by getreu** [comment]
> maybe need your html preprocessed

This would require double parsing of the input.

What about adding a hook, e.g. a closure that could insert a filter for unwanted nodes?

**Comment by nabbisen** [comment]
@getreu 
I released another crate to manipulate html:
https://github.com/nabbisen/htmlproc-rs

How about this one to preprocess ?

```sh
cargo add htmlproc --features omit_enclosures
```

```rust
use htmlproc::omit_enclosures::manipulate;

let result: String = manipulate("your_html_str", &["target_tag"]);
```

---

> This would require double parsing of the input.

Agreed. It must have good performance especially on big html, although the two are different function.

> What about adding a hook, e.g. a closure that could insert a filter for unwanted nodes?

OK. I'll try to design. It may be somehow tough to me 😅

**Comment by getreu** [comment]
> I released another crate to manipulate html:
https://github.com/nabbisen/htmlproc-rs

I tried your crate and filed https://github.com/nabbisen/htmlproc-rs/issues/5

There you also find some test input data.

BTW: The preferred solution is still to integrate the filter into this crate.

> OK. I'll try to design. It may be somehow tough to me 😅

May I help?

**Comment by nabbisen** [comment]
@getreu 
> May I help?
Thank you. My concern is how to keep the code base simple following the philosophy "Make each program do one thing well". This crate aims to convert HTML to Markdown instead of modifying HTML. Therefore, I am temporarily puzzled.

**Comment by nabbisen** [comment]
@getreu 
I added feature to [htmlproc-rs](https://github.com/nabbisen/htmlproc-rs?tab=readme-ov-file#omit_attr):

- [omit_attr](https://github.com/nabbisen/htmlproc-rs?tab=readme-ov-file#omit_attr).

You can omit attrs such as `style` from tags as well as tag enclosure with existing (renamed a bit) feature:

- [omit_enclosure](https://github.com/nabbisen/htmlproc-rs#omit_attr).

**Comment by getreu** [comment]
I tried to use both features: 

```rust
/// Ommit HTML `<span>` before converting to Markdown.
#[cfg(feature = "renderer")]
const TARGET_TAGS: &[&str; 2] = &["span", "div"];

/// Ommit HTML `<... style="..."n>` before converting to Markdown.
#[cfg(feature = "renderer")]
const TARGET_ATTR: &[&str; 1] = &["style"];
```

After piping the input through `mdka` I still get `<span id="...">` tags! Tags that did not appear in the input at all. These tags confuse the subsequent processing, in my case `pulldown_cmark`.

Here some sample input:

```html
<!DOCTYPE html><meta http-equiv="content-type" content="text/html; charset=utf-8"><div class="col-md-12 text-center"><h1>Vom Fußball lernen | Von Rüdiger Rauls</h1>
							<div class="post-article-meta">
			<p><strong>Veröffentlicht am:</strong> 3. Juli 2024 | <strong>Anzahl Kommentare:</strong> 3 Kommentare</p>
		</div>
								<div id="videoandpodcast">
				<ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="pills-video-tab" data-toggle="pill" href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-video" role="tab" aria-controls="pills-video" aria-selected="true"><i class="fas fa-video"></i> Anschauen</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" id="pills-podcast-tab" data-toggle="pill" href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-podcast" role="tab" aria-controls="pills-podcast" aria-selected="false"> <i class="fas fa-headphones-alt"></i> Anhören</a>
					</li>
				</ul>
				<div class="tab-content" id="pills-tabContent">
					<div class="tab-pane fade show active" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
					<div class="resiframe">
						<iframe title="Vom Fußball lernen | Von Rüdiger Rauls" width="560" height="315" src="https://tube4.apolut.net/videos/embed/8db51971-d169-490d-ba60-c2e2369d1996" frameborder="0" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups allow-forms"></iframe>					</div>

					</div>
					
				</div>
			</div>
				
 

			<div class="social-media-post-full d-flex">
				<a class="facebook" rel="nofollow" target="_blank" title="Bei Telegram empfehlen" href="https://t.me/share/url?url=https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F&amp;text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls"><i class="fab fa-telegram-plane"></i> <span>teilen</span></a>
				<a class="twitter" rel="nofollow" target="_blank" title="Bei Twitter empfehlen" href="https://twitter.com/intent/tweet?source=webclient&amp;text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F"><i class="fab fa-twitter"></i> <span>tweeten</span></a>
				<a class="mail" rel="nofollow" target="_blank" href="mailto:?subject=Vom Fußball lernen | Von Rüdiger Rauls&amp;body=https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/" title="Diesen Artikelper Email an einen Freund senden !"><i class="fa fa-envelope"></i> <span>mailen</span></a>
				<a class="comment" rel="nofollow" href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#comments"><i class="fa fa-comment" aria-hidden="true"></i> <span>kommentieren</span></a>
				<a class="mail" rel="nofollow" target="_blank" href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls//?print-posts=pdf" title="Vom Fußball lernen | Von Rüdiger Rauls als PDF downloaden"><i class="fas fa-file-pdf"></i> <span>pdf download</span></a>
			</div>

		</div>
		<div class="col-md-8 mx-auto single-post-content">						
			<p style="text-align: justify;"><em>Ein Standpunkt von <strong>Rüdiger Rauls.</strong></em></p>
<p style="text-align: justify;">Besonders für viele intellektuelle 
Kritiker besteht die Fußball-Fangemeinde aus Ungebildeten und politisch 
Desinteressierten. Dabei sind gerade die Fans die Speerspitze im Kampf 
gegen Investoren und dabei oft erfolgreicher als die zerstrittenen 
politischen Bewegungen.</p></div>
```

And `htmlproc` and `mdka` 's output: 

```markdown
# Vom Fußball lernen | Von Rüdiger Rauls

 **Veröffentlicht am:** 3. Juli 2024 | **Anzahl Kommentare:** 3 Kommentare



<span id="videoandpodcast">

<span id="pills-tab">
-     <span id="pills-video-tab"> [Anschauen](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-video) </span>
-     <span id="pills-podcast-tab"> [Anhören](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-podcast) </span>

</span>

<span id="pills-tabContent">
<span id="pills-video"></span>
</span>

</span>
 [teilen](https://t.me/share/url?url=https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F&text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls)  [tweeten](https://twitter.com/intent/tweet?source=webclient&text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F)  [mailen](mailto:?subject=Vom Fußball lernen | Von Rüdiger Rauls&body=https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/)  [kommentieren](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#comments)  [pdf download](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls//?print-posts=pdf) 

 *Ein Standpunkt von **Rüdiger Rauls.** * 

Besonders für viele intellektuelle 
Kritiker besteht die Fußball-Fangemeinde aus Ungebildeten und politisch 
Desinteressierten. Dabei sind gerade die Fans die Speerspitze im Kampf 
gegen Investoren und dabei oft erfolgreicher als die zerstrittenen 
politischen Bewegungen.
```

**Comment by nabbisen** [comment]
@getreu 
It is expected behavior on mdka because the tag had `id` which works in Markdown. Again, `id` and `style` are preserved with mdka because they work in Markdown.

**Comment by getreu** [comment]
>  which _works_ in Markdown

What does _works_ mean for you? Compliant with the [CommonMark](https://commonmark.org/) specification?

**Comment by nabbisen** [comment]
@getreu 
`id` is available as linked-to identifier. `style` is for styling.

Well, I understood the problem is `id`-attr tag should end instantly although `style`-attr tag should surround content.
I will fix it with another issue. Thank you.

Besides, another problem may stay because "tweeten" 's `href` contains space which `pulldown_cmark` failed to parse.

---

#### Fixed `mdka` output

```
# Vom Fußball lernen | Von Rüdiger Rauls

 **Veröffentlicht am:** 3. Juli 2024 | **Anzahl Kommentare:** 3 Kommentare

<span id="videoandpodcast"></span>

<span id="pills-tab"></span>
-     <span id="pills-video-tab"></span> [Anschauen](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-video)
-     <span id="pills-podcast-tab"></span> [Anhören](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-podcast)

<span id="pills-tabContent"></span>
<span id="pills-video"></span>

 [teilen](https://t.me/share/url?url=https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F&text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls)  [tweeten](https://twitter.com/intent/tweet?source=webclient&text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F)  [mailen](mailto:?subject=Vom Fußball lernen | Von Rüdiger Rauls&body=https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/)  [kommentieren](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#comments)  [pdf download](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls//?print-posts=pdf) 

 *Ein Standpunkt von **Rüdiger Rauls.** * 

Besonders für viele intellektuelle 
Kritiker besteht die Fußball-Fangemeinde aus Ungebildeten und politisch 
Desinteressierten. Dabei sind gerade die Fans die Speerspitze im Kampf 
gegen Investoren und dabei oft erfolgreicher als die zerstrittenen 
politischen Bewegungen.
```

#### `pulldown_cmark`

```
<h1>Vom Fußball lernen | Von Rüdiger Rauls</h1>
<p><strong>Veröffentlicht am:</strong> 3. Juli 2024 | <strong>Anzahl Kommentare:</strong> 3 Kommentare</p>
<p><span id="videoandpodcast"></span></p>
<p><span id="pills-tab"></span></p>
<ul>
<li>
<pre><code>&lt;span id="pills-video-tab"&gt;&lt;/span&gt; [Anschauen](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-video)
</code></pre>
</li>
<li>
<pre><code>&lt;span id="pills-podcast-tab"&gt;&lt;/span&gt; [Anhören](https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#pills-podcast)
</code></pre>
</li>
</ul>
<p><span id="pills-tabContent"></span>
<span id="pills-video"></span></p>
<p><a href="https://t.me/share/url?url=https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F&amp;text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls">teilen</a>  [tweeten](https://twitter.com/intent/tweet?source=webclient&amp;text=Vom%20Fu%C3%9Fball%20lernen%20%7C%20Von%20R%C3%BCdiger%20Rauls https%3A%2F%2Fapolut.net%2Fvom-fussball-lernen-von-ruediger-rauls%2F)  [mailen](mailto:?subject=Vom Fußball lernen | Von Rüdiger Rauls&amp;body=https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/)  <a href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls/#comments">kommentieren</a>  <a href="https://apolut.net/vom-fussball-lernen-von-ruediger-rauls//?print-posts=pdf">pdf download</a></p>
<p>*Ein Standpunkt von <strong>Rüdiger Rauls.</strong> *</p>
<p>Besonders für viele intellektuelle
Kritiker besteht die Fußball-Fangemeinde aus Ungebildeten und politisch
Desinteressierten. Dabei sind gerade die Fans die Speerspitze im Kampf
gegen Investoren und dabei oft erfolgreicher als die zerstrittenen
politischen Bewegungen.</p>

```

##### Testing Rust code

```rust
use pulldown_cmark::{html, Options, Parser};

fn main() {
    let markdown = r#"
...
    "#;
    let mut options = Options::empty();
    for option in vec![
        Options::ENABLE_TABLES,
        Options::ENABLE_STRIKETHROUGH,
    ] {
        options.insert(option);
    }
    let parser = Parser::new_ext(markdown, options);
    let mut html_output = String::new();
    html::push_html(&mut html_output, parser);
    
    println!("{}", html_output.as_str());
}
```

**Comment by getreu** [comment]
> Besides, another problem may stay because "tweeten" 's href contains space which pulldown_cmark failed to parse.

It seems that double quotes around the title are missing, see [example-506](https://spec.commonmark.org/0.31.2/#example-506)

**Comment by getreu** [comment]
BTW: You might find this collection of [test cases](https://spec.commonmark.org/0.31.2/spec.json) useful for your unit tests.

**Comment by getreu** [comment]
> id and style are preserved with mdka because they work in Markdown.

In my use case they are just noise, that require another post parsing to eliminate them. Could you consider a config flag that prevents `<span...>` being dumped?

**Comment by nabbisen** [comment]
> BTW: You might find this collection of [test cases](https://spec.commonmark.org/0.31.2/spec.json) useful for your unit tests.

It's a good idea but current status of this project fulfills my needs on another project with the current test cases. In addition, I'm focusing other projects.

**Comment by nabbisen** [comment]
> > id and style are preserved with mdka because they work in Markdown.
> 
> In my use case they are just noise, that require another post parsing to eliminate them. Could you consider a config flag that prevents `<span...>` being dumped?

I thought of it before. There are problems about complixity and work time. In addition, it is not what the project requires now. Therefore, I can't make any instant promise.

You can try other libraries and create your own.

**Comment by getreu** [comment]
This is Ok. Maybe it would be good to document, that you inject HTML `<span>` tags into the Markdown rendition. It took me some time to find out where they come from.
